---
deployment:
  tasks:
    - export DEPLOYPATH=/home/elcerrit/public_html/HCEI
    - /bin/rsync -av --delete \
        --exclude='.git' \
        --exclude='.cpanel.yml' \
        --exclude='conn.php' \
        ./ $DEPLOYPATH
