<?php

// --- CONFIGURACIÓN DE LA EMPRESA ---
// Modifica estos valores para cada copia de la aplicación.
$empresa = [
    'nombre' => 'Fundación Ambulancias Lentas ',
    'nit' => '800000000-1',
    'direccion' => 'Calle 1 #2-34, Valle del Cauca',
    'web' => 'ambulancia.com',
    'titulo_general' => 'Ambulancias 2025',
    'logo_principal' => 'ambulance.png',
    'logo_vigilado' => 'vigilado.png',
    'titulo_pdf' => 'Registro de Atención Prehospitalaria y Traslado de Pacientes 2025',
    'version' => '3.4',
    'declaracion_legal' => 'Como firmante, mayor de edad, obrando en nombre propio y en mi condición de Acompañante o Testigo, por medio del presente documento manifiesto que he autorizado la atención y aplicación de los tratamientos propuestos por el personal de salud y, en caso de ser necesario, el traslado en ambulancia. Así mismo, autorizo a que se realicen los procedimientos necesarios para la estabilización clínica. Entiendo y acepto los riesgos justificados que conlleva el procedimiento y me comprometo a cumplir con las recomendaciones e instrucciones.',
    'ambulancias' => [
        'Móvil 1 AAA-111',
        'Móvil 2 BBB-222',
        'Móvil 3 CCC-333',
        'Móvil 4 DDD-444',
        'Móvil 5 EEE-555'
    ]
];


$titulos = [
    'registro' => 'Registro No.',
    'fecha' => 'Fecha',
    'ambulancia' => 'Ambulancia',
    'servicio' => 'Servicio',
    'pagador' => 'Pagador',
    'tipo_traslado' => 'Tipo traslado',
    'quien_informo' => '¿Quién informó?',
    'hora_despacho' => 'Hora despacho',
    'hora_llegada' => 'Hora llegada',
    'hora_ingreso' => 'Hora ingreso',
    'hora_final' => 'Hora final',
    'conductor' => 'Conductor',
    'cc_conductor' => 'cc conductor',
    'tripulante' => 'Tripulante',
    'tipo_id_tripulante' => 'Tipo ID Tripulante',
    'cc_tripulante' => 'Número ID Tripulante',
    'medico_tripulante' => 'Médico tripulante',
    'tipo_id_medico' => 'Tipo ID Médico',
    'cc_medico' => 'Número ID Médico',
    'direccion_servicio' => 'Dirección de servicio',
    'localizacion' => 'Localización',
    'ips_destino' => 'IPS destino',
    'traslado_tipo' => 'Traslado tipo',
    'aseguradora_soat' => 'Aseguradora SOAT',
    'ips2' => 'IPS2',
    'ips3' => 'IPS3',
    'ips4' => 'IPS4',
    'eps_nombre' => 'Nombre EPS',
    'nombres_paciente' => 'Nombre',
    'tipo_identificacion' => 'Tipo identificación',
    'id_paciente' => 'Identificación paciente',
    'genero_nacer' => 'Género al nacer',
    'fecha_nacimiento' => 'Nacimiento',
    'direccion_domicilio' => 'Dirección domicilio',
    'telefono_paciente' => 'Teléfono paciente',
    'barrio_paciente' => 'Barrio paciente',
    'ciudad' => 'Ciudad',
    'antecedentes' => 'Antecedentes',
    'frecuencia_cardiaca' => 'FC',
    'frecuencia_respiratoria' => 'FR',
    'spo2' => 'Spo2',
    'tension_arterial' => 'Tensión arterial',
    'glucometria' => 'Glucometría',
    'temperatura' => 'Temperatura',
    'rh' => 'Rh',
    'llenado_capilar' => 'Llenado capilar',
    'peso' => 'Peso',
    'talla' => 'Talla',
    'examen_fisico' => 'Describa el Examen Físico',
    'procedimientos' => 'Procedimientos',
    'consumo_servicio' => 'Consumo durante el Servicio',
    'escala_glasgow' => 'E Glasgow',
    'foto_registro' => 'Fotos de registro',
    'firma_paramedico' => 'Firma paramédico',
    'firma_medico' => 'Firma médico',
    'firma_paciente' => 'Firma paciente',
    'nombre_medico_receptor' => 'Nombre Médico Receptor',
    'tipo_id_medico_receptor' => 'Tipo ID Médico Receptor',
    'id_medico_receptor' => 'Número ID Médico Receptor',
    'firma_medico_receptor' => 'Firma Médico Receptor',
    'aceptacion' => 'Aceptación',
    'adjuntos' => 'Adjuntos',
    'created_at' => 'Creado el',
    'fecha_hora_atencion' => 'Fecha y hora de atención',
    // Nuevos campos
    'atencion_en' => 'Atención en',
    'etnia' => 'Étnia',
    'especificar_otra' => 'Otra etnia (especificar)',
    'discapacidad' => 'Discapacidad',
    // Antecedentes médicos
    'ant_alergicos_sn' => 'Antecedentes Alérgicos',
    'ant_alergicos_cual' => 'Antecedentes Alérgicos (¿Cuál?)',
    'ant_ginecoobstetricos_sn' => 'Antecedentes GinecoObstétricos (Sí/No)',
    'ant_ginecoobstetricos_cual' => 'Antecedentes GinecoObstétricos (¿Cuál?)',
    'ant_patologicos_sn' => 'Antecedentes Patológicos (Sí/No)',
    'ant_patologicos_cual' => 'Antecedentes Patológicos (¿Cuál?)',
    'ant_quirurgicos_sn' => 'Antecedentes Quirúrgicos (Sí/No)',
    'ant_quirurgicos_cual' => 'Antecedentes Quirúrgicos (¿Cuál?)',
    'ant_traumatologicos_sn' => 'Antecedentes Traumatológicos (Sí/No)',
    'ant_traumatologicos_cual' => 'Antecedentes Traumatológicos (¿Cuál?)',
    'ant_toxicologicos_sn' => 'Antecedentes Toxicológicos (Sí/No)',
    'ant_toxicologicos_cual' => 'Antecedentes Toxicológicos (¿Cuál?)',
    'ant_familiares_sn' => 'Antecedentes Familiares',
    'ant_familiares_cual' => 'Antecedentes Familiares (¿Cuál?)'
];