<?php
return [
    'TAM' => [
        'Documentacion y elementos administrativos' => [
            ['codigo' => 'DOC-TAM-001', 'nombre' => 'Licencia de funcionamiento y habilitacion vigente'],
            ['codigo' => 'DOC-TAM-002', 'nombre' => 'Tarjeta de operacion de la ambulancia'],
            ['codigo' => 'DOC-TAM-003', 'nombre' => 'SOAT vigente'],
            ['codigo' => 'DOC-TAM-004', 'nombre' => 'Poliza de responsabilidad civil extracontractual'],
            ['codigo' => 'DOC-TAM-005', 'nombre' => 'Certificados de revision tecnico-mecanica y de gases'],
            ['codigo' => 'DOC-TAM-006', 'nombre' => 'Formato de auditoria interna del inventario TAM'],
            ['codigo' => 'DOC-TAM-007', 'nombre' => 'Relacion de tripulantes autorizados'],
            ['codigo' => 'DOC-TAM-008', 'nombre' => 'Hoja de vida del vehiculo'],
            ['codigo' => 'DOC-TAM-009', 'nombre' => 'Formato de control de mantenimiento preventivo y correctivo']
        ],
        'Dotacion de cabina asistencial' => [
            ['codigo' => 'CAB-TAM-001', 'nombre' => 'Camilla principal tipo rodante con anclajes'],
            ['codigo' => 'CAB-TAM-002', 'nombre' => 'Camilla secundaria o de tablas con correas'],
            ['codigo' => 'CAB-TAM-003', 'nombre' => 'Silla de ruedas plegable con cinturon'],
            ['codigo' => 'CAB-TAM-004', 'nombre' => 'Banco/butaca con cinturones de seguridad'],
            ['codigo' => 'CAB-TAM-005', 'nombre' => 'Sistema de iluminacion interna regulable'],
            ['codigo' => 'CAB-TAM-006', 'nombre' => 'Fuente electrica de respaldo'],
            ['codigo' => 'CAB-TAM-007', 'nombre' => 'Extintor multiproposito'],
            ['codigo' => 'CAB-TAM-008', 'nombre' => 'Botiquin empotrado con cerradura'],
            ['codigo' => 'CAB-TAM-009', 'nombre' => 'Termometro ambiental'],
            ['codigo' => 'CAB-TAM-010', 'nombre' => 'Basurero con tapa y bolsa roja'],
            ['codigo' => 'CAB-TAM-011', 'nombre' => 'Contenedor plastico para RPBI'],
            ['codigo' => 'CAB-TAM-012', 'nombre' => 'Ventilacion y climatizacion en cabina asistencial']
        ],
        // Equipos biomédicos (presentes solo en TAM según encabezados originales)
        'Equipos medicos' => [
            ['codigo' => 'EQU-TAM-001', 'nombre' => 'Monitor desfibrilador con registro (ECG, SpO2, NIBP)'],
            ['codigo' => 'EQU-TAM-002', 'nombre' => 'Desfibrilador externo semiautomatico'],
            ['codigo' => 'EQU-TAM-003', 'nombre' => 'Ventilador mecanico de transporte'],
            ['codigo' => 'EQU-TAM-004', 'nombre' => 'Equipo de aspiracion fija y portatil'],
            ['codigo' => 'EQU-TAM-005', 'nombre' => 'Bombas de infusion (2 unidades)'],
            ['codigo' => 'EQU-TAM-006', 'nombre' => 'Oximetro de pulso portatil'],
            ['codigo' => 'EQU-TAM-007', 'nombre' => 'Tensiometros aneroides adulto, pediatrico y neonatal'],
            ['codigo' => 'EQU-TAM-008', 'nombre' => 'Estetoscopios adulto y pediatrico'],
            ['codigo' => 'EQU-TAM-009', 'nombre' => 'Equipo de intubacion adulto y pediatrico completo'],
            ['codigo' => 'EQU-TAM-010', 'nombre' => 'Laringoscopios con hojas rectas y curvas'],
            ['codigo' => 'EQU-TAM-011', 'nombre' => 'Nebulizador'],
            ['codigo' => 'EQU-TAM-012', 'nombre' => 'Termometro clinico digital infrarrojo'],
            ['codigo' => 'EQU-TAM-013', 'nombre' => 'Glucometro con tiras reactivas'],
            ['codigo' => 'EQU-TAM-014', 'nombre' => 'Bombas de succion manuales'],
            ['codigo' => 'EQU-TAM-015', 'nombre' => 'Equipo de oxigeno central con manometro y flujometro'],
            ['codigo' => 'EQU-TAM-016', 'nombre' => 'Balas de oxigeno portatiles con carrito'],
            ['codigo' => 'EQU-TAM-017', 'nombre' => 'Mascarillas de nebulizacion adulto/pediatrico'],
            ['codigo' => 'EQU-TAM-018', 'nombre' => 'Equipo de CPAP/BIPAP portatil'],
            ['codigo' => 'EQU-TAM-019', 'nombre' => 'Equipo de capnografia portatil'],
            ['codigo' => 'EQU-TAM-020', 'nombre' => 'Cargadores y cables para equipos biomedicos']
        ],
        'Medicamentos y soluciones' => [
            ['codigo' => 'MED-TAM-001', 'nombre' => 'Adrenalina 1:1000 ampolla'],
            ['codigo' => 'MED-TAM-002', 'nombre' => 'Amiodarona 150 mg ampolla'],
            ['codigo' => 'MED-TAM-003', 'nombre' => 'Atropina 1 mg ampolla'],
            ['codigo' => 'MED-TAM-004', 'nombre' => 'Bicarbonato de sodio 7.5% ampolla'],
            ['codigo' => 'MED-TAM-005', 'nombre' => 'Cloruro de sodio 0.9% 500 ml'],
            ['codigo' => 'MED-TAM-006', 'nombre' => 'Dextrosa al 50% ampolla'],
            ['codigo' => 'MED-TAM-007', 'nombre' => 'Diazepam 10 mg ampolla'],
            ['codigo' => 'MED-TAM-008', 'nombre' => 'Dobutamina 250 mg/5ml ampolla'],
            ['codigo' => 'MED-TAM-009', 'nombre' => 'Ketamina 500 mg/10 ml ampolla'],
            ['codigo' => 'MED-TAM-010', 'nombre' => 'Lidocaina 2% ampolla'],
            ['codigo' => 'MED-TAM-011', 'nombre' => 'Metilprednisolona 500 mg vial'],
            ['codigo' => 'MED-TAM-012', 'nombre' => 'Midazolam 5 mg/ml ampolla'],
            ['codigo' => 'MED-TAM-013', 'nombre' => 'Morfina 10 mg/ml ampolla'],
            ['codigo' => 'MED-TAM-014', 'nombre' => 'Naloxona 0.4 mg/ml ampolla'],
            ['codigo' => 'MED-TAM-015', 'nombre' => 'Nitroglicerina spray sublingual'],
            ['codigo' => 'MED-TAM-016', 'nombre' => 'Ondansetron 4 mg ampolla'],
            ['codigo' => 'MED-TAM-017', 'nombre' => 'Paracetamol 1 g/100 ml bolsa'],
            ['codigo' => 'MED-TAM-018', 'nombre' => 'Ringer Lactato 500 ml'],
            ['codigo' => 'MED-TAM-019', 'nombre' => 'Salbutamol inhalador dosificador'],
            ['codigo' => 'MED-TAM-020', 'nombre' => 'Succinilcolina 100 mg/2 ml ampolla']
        ],
        'Material quirurgico y de curacion' => [
            ['codigo' => 'MAT-TAM-001', 'nombre' => 'Guantes esteriles talla S, M, L'],
            ['codigo' => 'MAT-TAM-002', 'nombre' => 'Gasas esteriles 10x10 cm'],
            ['codigo' => 'MAT-TAM-003', 'nombre' => 'Vendas elasticas 4", 6"'],
            ['codigo' => 'MAT-TAM-004', 'nombre' => 'Esparadrapo hipoalergenico'],
            ['codigo' => 'MAT-TAM-005', 'nombre' => 'Jeringas desechables 1, 3, 5, 10, 20 ml'],
            ['codigo' => 'MAT-TAM-006', 'nombre' => 'Cateteres IV calibre 14-24'],
            ['codigo' => 'MAT-TAM-007', 'nombre' => 'Suturas absorbibles y no absorbibles'],
            ['codigo' => 'MAT-TAM-008', 'nombre' => 'Solucion antiseptica (povidona, alcohol)'],
            ['codigo' => 'MAT-TAM-009', 'nombre' => 'Mascarillas quirurgicas'],
            ['codigo' => 'MAT-TAM-010', 'nombre' => 'Protector ocular descartable'],
            ['codigo' => 'MAT-TAM-011', 'nombre' => 'Colchon de vacio'],
            ['codigo' => 'MAT-TAM-012', 'nombre' => 'Juegos de venoclisis'],
            ['codigo' => 'MAT-TAM-013', 'nombre' => 'Sondas vesicales y de aspiracion'],
            ['codigo' => 'MAT-TAM-014', 'nombre' => 'Lubricante hidrosoluble'],
            ['codigo' => 'MAT-TAM-015', 'nombre' => 'Canulas orofaringeas (Guedel)'],
            ['codigo' => 'MAT-TAM-016', 'nombre' => 'Mascarillas laringeas'],
            ['codigo' => 'MAT-TAM-017', 'nombre' => 'Electrodos desechables para monitor'],
            ['codigo' => 'MAT-TAM-018', 'nombre' => 'Tiras reactivas para glucometro'],
            ['codigo' => 'MAT-TAM-019', 'nombre' => 'Bolsas para recoleccion de fluidos'],
            ['codigo' => 'MAT-TAM-020', 'nombre' => 'Cinta metrica y tallimetro portatil']
        ],
        'Inmovilizadores y dispositivos de traslado' => [
            ['codigo' => 'TRA-TAM-001', 'nombre' => 'Tabla espinal larga con correas'],
            ['codigo' => 'TRA-TAM-002', 'nombre' => 'Inmovilizador cervical rigido talla S, M, L'],
            ['codigo' => 'TRA-TAM-003', 'nombre' => 'Chaleco de extricacion (KED)'],
            ['codigo' => 'TRA-TAM-004', 'nombre' => 'Ferulas rigidas para extremidades'],
            ['codigo' => 'TRA-TAM-005', 'nombre' => 'Ferulas inflables'],
            ['codigo' => 'TRA-TAM-006', 'nombre' => 'Colchon de vacio corporal'],
            ['codigo' => 'TRA-TAM-007', 'nombre' => 'Arnes para camilla'],
            ['codigo' => 'TRA-TAM-008', 'nombre' => 'Cojines inmovilizadores de craneo'],
            ['codigo' => 'TRA-TAM-009', 'nombre' => 'Correas de sujecion de pacientes pediatricos'],
            ['codigo' => 'TRA-TAM-010', 'nombre' => 'Sistema de anclaje para incubadora de transporte']
        ],
        'Bioseguridad y aseo' => [
            ['codigo' => 'BIO-TAM-001', 'nombre' => 'Guantes de nitrilo desechables'],
            ['codigo' => 'BIO-TAM-002', 'nombre' => 'Tapabocas N95'],
            ['codigo' => 'BIO-TAM-003', 'nombre' => 'Gafas de proteccion'],
            ['codigo' => 'BIO-TAM-004', 'nombre' => 'Careta facial'],
            ['codigo' => 'BIO-TAM-005', 'nombre' => 'Batas desechables'],
            ['codigo' => 'BIO-TAM-006', 'nombre' => 'Gorros desechables'],
            ['codigo' => 'BIO-TAM-007', 'nombre' => 'Botas plasticas desechables'],
            ['codigo' => 'BIO-TAM-008', 'nombre' => 'Gel antibacterial'],
            ['codigo' => 'BIO-TAM-009', 'nombre' => 'Solucion desinfectante de alto nivel'],
            ['codigo' => 'BIO-TAM-010', 'nombre' => 'Panos absorbentes desechables'],
            ['codigo' => 'BIO-TAM-011', 'nombre' => 'Kit de derrames biologicos'],
            ['codigo' => 'BIO-TAM-012', 'nombre' => 'Recipiente para objetos cortopunzantes'],
            ['codigo' => 'BIO-TAM-013', 'nombre' => 'Bolsas rojas y negras para residuos'],
            ['codigo' => 'BIO-TAM-014', 'nombre' => 'Detergente hospitalario'],
            ['codigo' => 'BIO-TAM-015', 'nombre' => 'Toallas de papel desechables']
        ],
        'Equipos de comunicacion' => [
            ['codigo' => 'COM-TAM-001', 'nombre' => 'Radio de comunicacion VHF/UHF'],
            ['codigo' => 'COM-TAM-002', 'nombre' => 'Telefono movil operativo'],
            ['codigo' => 'COM-TAM-003', 'nombre' => 'Sirena y sistema de megafono'],
            ['codigo' => 'COM-TAM-004', 'nombre' => 'GPS actualizado'],
            ['codigo' => 'COM-TAM-005', 'nombre' => 'Sistema de reporte en linea (tablet/computador)'],
            ['codigo' => 'COM-TAM-006', 'nombre' => 'Cargadores y repuestos de baterias']
        ],
        'Campos de auditoria interna' => [
            ['codigo' => 'AUD-TAM-001', 'nombre' => 'Estado general del inventario'],
            ['codigo' => 'AUD-TAM-002', 'nombre' => 'Observaciones del auditor'],
            ['codigo' => 'AUD-TAM-003', 'nombre' => 'Responsable de verificacion'],
            ['codigo' => 'AUD-TAM-004', 'nombre' => 'Fecha de ultima auditoria'],
            ['codigo' => 'AUD-TAM-005', 'nombre' => 'Plan de accion asociado']
        ]
    ],
    'TAB' => [
        'Documentacion y elementos administrativos' => [
            ['codigo' => 'DOC-TAB-001', 'nombre' => 'Licencia de funcionamiento y habilitacion vigente'],
            ['codigo' => 'DOC-TAB-002', 'nombre' => 'Tarjeta de operacion de la ambulancia'],
            ['codigo' => 'DOC-TAB-003', 'nombre' => 'SOAT vigente'],
            ['codigo' => 'DOC-TAB-004', 'nombre' => 'Poliza de responsabilidad civil extracontractual'],
            ['codigo' => 'DOC-TAB-005', 'nombre' => 'Certificado de revision tecnico-mecanica'],
            ['codigo' => 'DOC-TAB-006', 'nombre' => 'Formato de auditoria interna del inventario TAB'],
            ['codigo' => 'DOC-TAB-007', 'nombre' => 'Relacion de tripulantes autorizados'],
            ['codigo' => 'DOC-TAB-008', 'nombre' => 'Hoja de vida del vehiculo'],
            ['codigo' => 'DOC-TAB-009', 'nombre' => 'Formato de control de mantenimiento preventivo y correctivo']
        ],
        'Dotacion de cabina asistencial' => [
            ['codigo' => 'CAB-TAB-001', 'nombre' => 'Camilla principal tipo rodante con anclajes'],
            ['codigo' => 'CAB-TAB-002', 'nombre' => 'Tabla rigida con correas'],
            ['codigo' => 'CAB-TAB-003', 'nombre' => 'Silla de ruedas plegable'],
            ['codigo' => 'CAB-TAB-004', 'nombre' => 'Banco/butaca con cinturones de seguridad'],
            ['codigo' => 'CAB-TAB-005', 'nombre' => 'Sistema de iluminacion interna'],
            ['codigo' => 'CAB-TAB-006', 'nombre' => 'Extintor multiproposito'],
            ['codigo' => 'CAB-TAB-007', 'nombre' => 'Botiquin empotrado'],
            ['codigo' => 'CAB-TAB-008', 'nombre' => 'Basurero con tapa y bolsa roja'],
            ['codigo' => 'CAB-TAB-009', 'nombre' => 'Contenedor para RPBI'],
            ['codigo' => 'CAB-TAB-010', 'nombre' => 'Ventilacion en cabina asistencial']
        ],
        'Equipos medicos' => [
            ['codigo' => 'EQU-TAB-001', 'nombre' => 'Desfibrilador externo automatico (DEA)'],
            ['codigo' => 'EQU-TAB-002', 'nombre' => 'Equipo de aspiracion portatil'],
            ['codigo' => 'EQU-TAB-003', 'nombre' => 'Oximetro de pulso portatil'],
            ['codigo' => 'EQU-TAB-004', 'nombre' => 'Tensiometro aneroide adulto y pediatrico'],
            ['codigo' => 'EQU-TAB-005', 'nombre' => 'Estetoscopios adulto y pediatrico'],
            ['codigo' => 'EQU-TAB-006', 'nombre' => 'Termometro clinico digital'],
            ['codigo' => 'EQU-TAB-007', 'nombre' => 'Glucometro con tiras reactivas'],
            ['codigo' => 'EQU-TAB-008', 'nombre' => 'Equipo de oxigeno central con manometro y flujometro'],
            ['codigo' => 'EQU-TAB-009', 'nombre' => 'Balas de oxigeno portatiles'],
            ['codigo' => 'EQU-TAB-010', 'nombre' => 'Mascarillas de nebulizacion adulto/pediatrico'],
            ['codigo' => 'EQU-TAB-011', 'nombre' => 'Equipo de intubacion basico'],
            ['codigo' => 'EQU-TAB-012', 'nombre' => 'Ambu adulto, pediatrico y neonatal'],
            ['codigo' => 'EQU-TAB-013', 'nombre' => 'Canulas orofaringeas (Guedel)'],
            ['codigo' => 'EQU-TAB-014', 'nombre' => 'Termo-nevera para medicamentos'],
            ['codigo' => 'EQU-TAB-015', 'nombre' => 'Equipo de aspiracion manual (perilla o bombin)']
        ],
        'Medicamentos y soluciones' => [
            ['codigo' => 'MED-TAB-001', 'nombre' => 'Adrenalina 1:1000 ampolla'],
            ['codigo' => 'MED-TAB-002', 'nombre' => 'Atropina 1 mg ampolla'],
            ['codigo' => 'MED-TAB-003', 'nombre' => 'Dextrosa al 50% ampolla'],
            ['codigo' => 'MED-TAB-004', 'nombre' => 'Diazepam 10 mg ampolla'],
            ['codigo' => 'MED-TAB-005', 'nombre' => 'Lidocaina 2% ampolla'],
            ['codigo' => 'MED-TAB-006', 'nombre' => 'Salbutamol inhalador'],
            ['codigo' => 'MED-TAB-007', 'nombre' => 'Solucion salina 0.9% 500 ml'],
            ['codigo' => 'MED-TAB-008', 'nombre' => 'Ringer Lactato 500 ml'],
            ['codigo' => 'MED-TAB-009', 'nombre' => 'Paracetamol 1 g/100 ml'],
            ['codigo' => 'MED-TAB-010', 'nombre' => 'Ondansetron 4 mg ampolla'],
            ['codigo' => 'MED-TAB-011', 'nombre' => 'Naloxona 0.4 mg/ml ampolla'],
            ['codigo' => 'MED-TAB-012', 'nombre' => 'Hidrocortisona 100 mg vial'],
            ['codigo' => 'MED-TAB-013', 'nombre' => 'Solucion glucosada al 5% 500 ml'],
            ['codigo' => 'MED-TAB-014', 'nombre' => 'Solucion Hartmann 500 ml'],
            ['codigo' => 'MED-TAB-015', 'nombre' => 'Alcohol glicerinado 120 ml']
        ],
        'Material quirurgico y de curacion' => [
            ['codigo' => 'MAT-TAB-001', 'nombre' => 'Guantes esteriles talla S, M, L'],
            ['codigo' => 'MAT-TAB-002', 'nombre' => 'Gasas esteriles 10x10 cm'],
            ['codigo' => 'MAT-TAB-003', 'nombre' => 'Vendas elasticas 4", 6"'],
            ['codigo' => 'MAT-TAB-004', 'nombre' => 'Esparadrapo hipoalergenico'],
            ['codigo' => 'MAT-TAB-005', 'nombre' => 'Jeringas desechables 1, 3, 5, 10, 20 ml'],
            ['codigo' => 'MAT-TAB-006', 'nombre' => 'Cateteres IV calibre 16-24'],
            ['codigo' => 'MAT-TAB-007', 'nombre' => 'Solucion antiseptica (povidona, alcohol)'],
            ['codigo' => 'MAT-TAB-008', 'nombre' => 'Mascarillas quirurgicas'],
            ['codigo' => 'MAT-TAB-009', 'nombre' => 'Protector ocular descartable'],
            ['codigo' => 'MAT-TAB-010', 'nombre' => 'Juegos de venoclisis'],
            ['codigo' => 'MAT-TAB-011', 'nombre' => 'Sondas de aspiracion'],
            ['codigo' => 'MAT-TAB-012', 'nombre' => 'Lubricante hidrosoluble'],
            ['codigo' => 'MAT-TAB-013', 'nombre' => 'Venda triangular'],
            ['codigo' => 'MAT-TAB-014', 'nombre' => 'Tijeras multiproposito'],
            ['codigo' => 'MAT-TAB-015', 'nombre' => 'Cinta metrica y tallimetro portatil']
        ],
        'Inmovilizadores y dispositivos de traslado' => [
            ['codigo' => 'TRA-TAB-001', 'nombre' => 'Tabla espinal larga con correas'],
            ['codigo' => 'TRA-TAB-002', 'nombre' => 'Inmovilizador cervical rigido talla S, M, L'],
            ['codigo' => 'TRA-TAB-003', 'nombre' => 'Ferulas rigidas para extremidades'],
            ['codigo' => 'TRA-TAB-004', 'nombre' => 'Ferulas inflables'],
            ['codigo' => 'TRA-TAB-005', 'nombre' => 'Arnes para camilla'],
            ['codigo' => 'TRA-TAB-006', 'nombre' => 'Cojines inmovilizadores de craneo'],
            ['codigo' => 'TRA-TAB-007', 'nombre' => 'Correas de sujecion pediatricas'],
            ['codigo' => 'TRA-TAB-008', 'nombre' => 'Silla de evacuacion'],
            ['codigo' => 'TRA-TAB-009', 'nombre' => 'Collarines cervicales pediatricos']
        ],
        'Bioseguridad y aseo' => [
            ['codigo' => 'BIO-TAB-001', 'nombre' => 'Guantes de nitrilo desechables'],
            ['codigo' => 'BIO-TAB-002', 'nombre' => 'Tapabocas N95'],
            ['codigo' => 'BIO-TAB-003', 'nombre' => 'Gafas de proteccion'],
            ['codigo' => 'BIO-TAB-004', 'nombre' => 'Careta facial'],
            ['codigo' => 'BIO-TAB-005', 'nombre' => 'Batas desechables'],
            ['codigo' => 'BIO-TAB-006', 'nombre' => 'Gorros desechables'],
            ['codigo' => 'BIO-TAB-007', 'nombre' => 'Botas plasticas desechables'],
            ['codigo' => 'BIO-TAB-008', 'nombre' => 'Gel antibacterial'],
            ['codigo' => 'BIO-TAB-009', 'nombre' => 'Solucion desinfectante'],
            ['codigo' => 'BIO-TAB-010', 'nombre' => 'Panos absorbentes desechables'],
            ['codigo' => 'BIO-TAB-011', 'nombre' => 'Recipiente para cortopunzantes'],
            ['codigo' => 'BIO-TAB-012', 'nombre' => 'Bolsas rojas y negras para residuos']
        ],
        'Equipos de comunicacion' => [
            ['codigo' => 'COM-TAB-001', 'nombre' => 'Radio de comunicacion VHF/UHF'],
            ['codigo' => 'COM-TAB-002', 'nombre' => 'Telefono movil operativo'],
            ['codigo' => 'COM-TAB-003', 'nombre' => 'Sirena y sistema de megafono'],
            ['codigo' => 'COM-TAB-004', 'nombre' => 'GPS actualizado'],
            ['codigo' => 'COM-TAB-005', 'nombre' => 'Sistema de reporte en linea (tablet/computador)'],
            ['codigo' => 'COM-TAB-006', 'nombre' => 'Cargadores y repuestos de baterias']
        ],
        'Campos de auditoria interna' => [
            ['codigo' => 'AUD-TAB-001', 'nombre' => 'Estado general del inventario'],
            ['codigo' => 'AUD-TAB-002', 'nombre' => 'Observaciones del auditor'],
            ['codigo' => 'AUD-TAB-003', 'nombre' => 'Responsable de verificacion'],
            ['codigo' => 'AUD-TAB-004', 'nombre' => 'Fecha de ultima auditoria'],
            ['codigo' => 'AUD-TAB-005', 'nombre' => 'Plan de accion asociado']
        ]
    ]
];
?>


